### ISSUE TITLE
Does this still work in VS2022?

### ISSUE THREAD

**Issue by LWChris** [mayerwin/vs-disable-no-source-tab#4]
Hi, I'm a long-term user of the extension but it appears to no longer work for me. Every time I pause the application, I get this tab saying "The application is in break mode".

An example screenshot of the tab I get is here:

https://learn.microsoft.com/en-us/answers/questions/908394/any-way-to-disable-the-break-mode-popup

I get it in German though.

P.S.: The solution given in the linked forum to disable "just my code" technically gets rid of the tab but therefore opens a different tab with the framework code which isn't helpful either.

**Comment by mayerwin** [comment]
Thanks for the note, it looks like VS 2022 changed the tab title from "No Source Available" to "Break Mode", and also the auto-loading of the extension was no longer working. I just fixed this and updated the extension in the marketplace (version 4.0.2).

**Comment by LWChris** [comment]
Thank you for updating, but unfortunately I still get this tab:

![image](https://github.com/mayerwin/vs-disable-no-source-tab/assets/845152/5fadfb09-4ffc-404f-96d7-98c4e53c30a1)

even though I got version 4.0.3

![image](https://github.com/mayerwin/vs-disable-no-source-tab/assets/845152/734926b8-d1f8-496b-926a-ba416f6bd4c6)

By the way, there's two small mistakes in the descriptions:

1. The first "Note" of the marketplace description still says "Visual Studio 2019 support has been temporarily dropped" after the repository markdown was edited to mention 2017 as well.
2. In both the repo and marketplace description you added the "(though it has been more than 10 years now :)" addition which is missing the closing bracket after the emoji.

**Comment by mayerwin** [comment]
That's strange, when launching an experimental instance it works as expected. But not when using the extension in the normal VS instance. Not sure how to debug this :/.

Regarding the description issues, I can't change it without updating the extension version (stupid new requirement from the marketplace that has been there for a few years).

**Comment by LWChris** [comment]
Hmm, by looking at the code, I think the only option would be to log all the "else" cases in `private static void RemoveNoSourceToolWindow(IVsShell shell)` (in some way that works in non-experimental mode).

Maybe it's some sort of race condition: in an experimental instance, a lot of additional tracing code is executed during launch, which delays execution of your extension code. When it finally runs, the handlers your extension removes have been added and removal succeeds. In the normal VS instance, initialization is faster, and since MS did a lot lately to improve VS launch speed, they made more processes asynchronous, including the adding of handlers, which leads to a race condition that your extension now can be initialized before everything else is done, so your attempt to remove the handlers comes too early.

Just a wild guess of something that seems remotely plausible to me, as a programmer without any knowledge of the VS internal systems.

**Comment by mayerwin** [comment]
Thanks for the tips, I think I have found the issue (though I still don't understand why it was working with the Experimental instance). Try version 4.0.5 and let me know if it indeed works now.

**Comment by LWChris** [comment]
It appears to be fixed now, I have paused the application several times now and the tab didn't show up despite not landing in an active task loop either.

Thank you!
